export namespace curlopt {
    const ABSTRACT_UNIX_SOCKET: string;
    const ACCEPTTIMEOUT_MS: string;
    const ACCEPT_ENCODING: string;
    const ADDRESS_SCOPE: string;
    const ALTSVC: string;
    const ALTSVC_CTRL: string;
    const APPEND: string;
    const AUTOREFERER: string;
    const AWS_SIGV4: string;
    const BUFFERSIZE: string;
    const CAINFO: string;
    const CAINFO_BLOB: string;
    const CAPATH: string;
    const CERTINFO: string;
    const CHUNK_BGN_FUNCTION: string;
    const CHUNK_DATA: string;
    const CHUNK_END_FUNCTION: string;
    const CLOSESOCKETDATA: string;
    const CLOSESOCKETFUNCTION: string;
    const CONNECTTIMEOUT: string;
    const CONNECTTIMEOUT_MS: string;
    const CONNECT_ONLY: string;
    const CONNECT_TO: string;
    const CONV_FROM_NETWORK_FUNCTION: string;
    const CONV_FROM_UTF8_FUNCTION: string;
    const CONV_TO_NETWORK_FUNCTION: string;
    const COOKIE: string;
    const COOKIEFILE: string;
    const COOKIEJAR: string;
    const COOKIELIST: string;
    const COOKIESESSION: string;
    const COPYPOSTFIELDS: string;
    const CRLF: string;
    const CRLFILE: string;
    const CURLU: string;
    const CUSTOMREQUEST: string;
    const DEBUGDATA: string;
    const DEBUGFUNCTION: string;
    const DEFAULT_PROTOCOL: string;
    const DIRLISTONLY: string;
    const DISALLOW_USERNAME_IN_URL: string;
    const DNS_CACHE_TIMEOUT: string;
    const DNS_INTERFACE: string;
    const DNS_LOCAL_IP4: string;
    const DNS_LOCAL_IP6: string;
    const DNS_SERVERS: string;
    const DNS_SHUFFLE_ADDRESSES: string;
    const DNS_USE_GLOBAL_CACHE: string;
    const DOH_SSL_VERIFYHOST: string;
    const DOH_SSL_VERIFYPEER: string;
    const DOH_SSL_VERIFYSTATUS: string;
    const DOH_URL: string;
    const EGDSOCKET: string;
    const ENCODING: string;
    const ERRORBUFFER: string;
    const EXPECT_100_TIMEOUT_MS: string;
    const FAILONERROR: string;
    const FILE: string;
    const FILETIME: string;
    const FNMATCH_DATA: string;
    const FNMATCH_FUNCTION: string;
    const FOLLOWLOCATION: string;
    const FORBID_REUSE: string;
    const FRESH_CONNECT: string;
    const FTPAPPEND: string;
    const FTPLISTONLY: string;
    const FTPPORT: string;
    const FTPSSLAUTH: string;
    const FTP_ACCOUNT: string;
    const FTP_ALTERNATIVE_TO_USER: string;
    const FTP_CREATE_MISSING_DIRS: string;
    const FTP_FILEMETHOD: string;
    const FTP_RESPONSE_TIMEOUT: string;
    const FTP_SKIP_PASV_IP: string;
    const FTP_SSL: string;
    const FTP_SSL_CCC: string;
    const FTP_USE_EPRT: string;
    const FTP_USE_EPSV: string;
    const FTP_USE_PRET: string;
    const GSSAPI_DELEGATION: string;
    const HAPPY_EYEBALLS_TIMEOUT_MS: string;
    const HAPROXYPROTOCOL: string;
    const HEADER: string;
    const HEADERDATA: string;
    const HEADERFUNCTION: string;
    const HEADEROPT: string;
    const HSTS: string;
    const HSTSREADDATA: string;
    const HSTSREADFUNCTION: string;
    const HSTSWRITEDATA: string;
    const HSTSWRITEFUNCTION: string;
    const HSTS_CTRL: string;
    const HTTP09_ALLOWED: string;
    const HTTP200ALIASES: string;
    const HTTPAUTH: string;
    const HTTPGET: string;
    const HTTPHEADER: string;
    const HTTPPOST: string;
    const HTTPPROXYTUNNEL: string;
    const HTTP_CONTENT_DECODING: string;
    const HTTP_TRANSFER_DECODING: string;
    const HTTP_VERSION: string;
    const IGNORE_CONTENT_LENGTH: string;
    const INFILE: string;
    const INFILESIZE: string;
    const INFILESIZE_LARGE: string;
    const INTERFACE: string;
    const INTERLEAVEDATA: string;
    const INTERLEAVEFUNCTION: string;
    const IOCTLDATA: string;
    const IOCTLFUNCTION: string;
    const IPRESOLVE: string;
    const ISSUERCERT: string;
    const ISSUERCERT_BLOB: string;
    const KEEP_SENDING_ON_ERROR: string;
    const KEYPASSWD: string;
    const KRB4LEVEL: string;
    const KRBLEVEL: string;
    const LOCALPORT: string;
    const LOCALPORTRANGE: string;
    const LOGIN_OPTIONS: string;
    const LOW_SPEED_LIMIT: string;
    const LOW_SPEED_TIME: string;
    const MAIL_AUTH: string;
    const MAIL_FROM: string;
    const MAIL_RCPT: string;
    const MAIL_RCPT_ALLLOWFAILS: string;
    const MAXAGE_CONN: string;
    const MAXCONNECTS: string;
    const MAXFILESIZE: string;
    const MAXFILESIZE_LARGE: string;
    const MAXLIFETIME_CONN: string;
    const MAXREDIRS: string;
    const MAX_RECV_SPEED_LARGE: string;
    const MAX_SEND_SPEED_LARGE: string;
    const MIMEPOST: string;
    const MIME_OPTIONS: string;
    const NETRC: string;
    const NETRC_FILE: string;
    const NEW_DIRECTORY_PERMS: string;
    const NEW_FILE_PERMS: string;
    const NOBODY: string;
    const NOPROGRESS: string;
    const NOPROXY: string;
    const NOSIGNAL: string;
    const OPENSOCKETDATA: string;
    const OPENSOCKETFUNCTION: string;
    const PASSWORD: string;
    const PATH_AS_IS: string;
    const PINNEDPUBLICKEY: string;
    const PIPEWAIT: string;
    const PORT: string;
    const POST: string;
    const POST301: string;
    const POSTFIELDS: string;
    const POSTFIELDSIZE: string;
    const POSTFIELDSIZE_LARGE: string;
    const POSTQUOTE: string;
    const POSTREDIR: string;
    const PREQUOTE: string;
    const PREREQDATA: string;
    const PREREQFUNCTION: string;
    const PRE_PROXY: string;
    const PRIVATE: string;
    const PROGRESSDATA: string;
    const PROGRESSFUNCTION: string;
    const PROTOCOLS: string;
    const PROXY: string;
    const PROXYAUTH: string;
    const PROXYHEADER: string;
    const PROXYPASSWORD: string;
    const PROXYPORT: string;
    const PROXYTYPE: string;
    const PROXYUSERNAME: string;
    const PROXYUSERPWD: string;
    const PROXY_CAINFO: string;
    const PROXY_CAINFO_BLOB: string;
    const PROXY_CAPATH: string;
    const PROXY_CRLFILE: string;
    const PROXY_ISSUERCERT: string;
    const PROXY_ISSUERCERT_BLOB: string;
    const PROXY_KEYPASSWD: string;
    const PROXY_PINNEDPUBLICKEY: string;
    const PROXY_SERVICE_NAME: string;
    const PROXY_SSLCERT: string;
    const PROXY_SSLCERTTYPE: string;
    const PROXY_SSLCERT_BLOB: string;
    const PROXY_SSLKEY: string;
    const PROXY_SSLKEYTYPE: string;
    const PROXY_SSLKEY_BLOB: string;
    const PROXY_SSLVERSION: string;
    const PROXY_SSL_CIPHER_LIST: string;
    const PROXY_SSL_OPTIONS: string;
    const PROXY_SSL_VERIFYHOST: string;
    const PROXY_SSL_VERIFYPEER: string;
    const PROXY_TLS13_CIPHERS: string;
    const PROXY_TLSAUTH_PASSWORD: string;
    const PROXY_TLSAUTH_TYPE: string;
    const PROXY_TLSAUTH_USERNAME: string;
    const PROXY_TRANSFER_MODE: string;
    const PUT: string;
    const QUOTE: string;
    const RANDOM_FILE: string;
    const RANGE: string;
    const READDATA: string;
    const READFUNCTION: string;
    const REDIR_PROTOCOLS: string;
    const REFERER: string;
    const REQUEST_TARGET: string;
    const RESOLVE: string;
    const RESOLVER_START_DATA: string;
    const RESOLVER_START_FUNCTION: string;
    const RESUME_FROM: string;
    const RESUME_FROM_LARGE: string;
    const RTSPHEADER: string;
    const RTSP_CLIENT_CSEQ: string;
    const RTSP_REQUEST: string;
    const RTSP_SERVER_CSEQ: string;
    const RTSP_SESSION_ID: string;
    const RTSP_STREAM_URI: string;
    const RTSP_TRANSPORT: string;
    const SASL_AUTHZID: string;
    const SASL_IR: string;
    const SEEKDATA: string;
    const SEEKFUNCTION: string;
    const SERVER_RESPONSE_TIMEOUT: string;
    const SERVICE_NAME: string;
    const SHARE: string;
    const SOCKOPTDATA: string;
    const SOCKOPTFUNCTION: string;
    const SOCKS5_AUTH: string;
    const SOCKS5_GSSAPI_NEC: string;
    const SOCKS5_GSSAPI_SERVICE: string;
    const SSH_AUTH_TYPES: string;
    const SSH_COMPRESSION: string;
    const SSH_HOST_PUBLIC_KEY_MD5: string;
    const SSH_HOST_PUBLIC_KEY_SHA256: string;
    const SSH_KEYDATA: string;
    const SSH_KEYFUNCTION: string;
    const SSH_HOSTKEYDATA: string;
    const SSH_HOSTKEYFUNCTION: string;
    const SSH_KNOWNHOSTS: string;
    const SSH_PRIVATE_KEYFILE: string;
    const SSH_PUBLIC_KEYFILE: string;
    const SSLCERT: string;
    const SSLCERTPASSWD: string;
    const SSLCERTTYPE: string;
    const SSLCERT_BLOB: string;
    const SSLENGINE: string;
    const SSLENGINE_DEFAULT: string;
    const SSLKEY: string;
    const SSLKEYPASSWD: string;
    const SSLKEYTYPE: string;
    const SSLKEY_BLOB: string;
    const SSLVERSION: string;
    const SSL_CIPHER_LIST: string;
    const SSL_CTX_DATA: string;
    const SSL_CTX_FUNCTION: string;
    const SSL_EC_CURVES: string;
    const SSL_ENABLE_ALPN: string;
    const SSL_ENABLE_NPN: string;
    const SSL_FALSESTART: string;
    const SSL_OPTIONS: string;
    const SSL_SESSIONID_CACHE: string;
    const SSL_VERIFYHOST: string;
    const SSL_VERIFYPEER: string;
    const SSL_VERIFYSTATUS: string;
    const STDERR: string;
    const STREAM_DEPENDS: string;
    const STREAM_DEPENDS_E: string;
    const STREAM_WEIGHT: string;
    const SUPPRESS_CONNECT_HEADERS: string;
    const TCP_FASTOPEN: string;
    const TCP_KEEPALIVE: string;
    const TCP_KEEPIDLE: string;
    const TCP_KEEPINTVL: string;
    const TCP_NODELAY: string;
    const TELNETOPTIONS: string;
    const TFTP_BLKSIZE: string;
    const TFTP_NO_OPTIONS: string;
    const TIMECONDITION: string;
    const TIMEOUT: string;
    const TIMEOUT_MS: string;
    const TIMEVALUE: string;
    const TIMEVALUE_LARGE: string;
    const TLS13_CIPHERS: string;
    const TLSAUTH_PASSWORD: string;
    const TLSAUTH_TYPE: string;
    const TLSAUTH_USERNAME: string;
    const TRAILERDATA: string;
    const TRAILERFUNCTION: string;
    const TRANSFERTEXT: string;
    const TRANSFER_ENCODING: string;
    const UNIX_SOCKET_PATH: string;
    const UNRESTRICTED_AUTH: string;
    const UPKEEP_INTERVAL_MS: string;
    const UPLOAD: string;
    const UPLOAD_BUFFERSIZE: string;
    const URL: string;
    const USERAGENT: string;
    const USERNAME: string;
    const USERPWD: string;
    const USE_SSL: string;
    const VERBOSE: string;
    const WILDCARDMATCH: string;
    const WRITEDATA: string;
    const WRITEFUNCTION: string;
    const WRITEHEADER: string;
    const XFERINFODATA: string;
    const XFERINFOFUNCTION: string;
    const XOAUTH2_BEARER: string;
}
export type curlopt = string;
export type Curlopt = {
    ABSTRACT_UNIX_SOCKET?: string | undefined;
    ACCEPTTIMEOUT_MS?: number | bigint | undefined;
    ACCEPT_ENCODING?: string | undefined;
    ADDRESS_SCOPE?: number | bigint | undefined;
    ALTSVC?: string | undefined;
    ALTSVC_CTRL?: number | bigint | undefined;
    APPEND?: number | bigint | undefined;
    AUTOREFERER?: number | bigint | undefined;
    AWS_SIGV4?: string | undefined;
    BUFFERSIZE?: number | bigint | undefined;
    CAINFO?: string | undefined;
    CAINFO_BLOB?: Uint8Array | undefined;
    CAPATH?: string | undefined;
    CERTINFO?: number | bigint | undefined;
    CONNECTTIMEOUT?: number | bigint | undefined;
    CONNECTTIMEOUT_MS?: number | bigint | undefined;
    CONNECT_ONLY?: number | bigint | undefined;
    CONNECT_TO?: string[] | undefined;
    COOKIE?: string | undefined;
    COOKIEFILE?: string | undefined;
    COOKIEJAR?: string | undefined;
    COOKIELIST?: string | undefined;
    COOKIESESSION?: number | bigint | undefined;
    COPYPOSTFIELDS?: string | Uint8Array | undefined;
    CRLF?: number | bigint | undefined;
    CRLFILE?: string | undefined;
    CUSTOMREQUEST?: string | undefined;
    DEFAULT_PROTOCOL?: string | undefined;
    DIRLISTONLY?: number | bigint | undefined;
    DISALLOW_USERNAME_IN_URL?: number | bigint | undefined;
    DNS_CACHE_TIMEOUT?: number | bigint | undefined;
    DNS_INTERFACE?: string | undefined;
    DNS_LOCAL_IP4?: string | undefined;
    DNS_LOCAL_IP6?: string | undefined;
    DNS_SERVERS?: string | undefined;
    DNS_SHUFFLE_ADDRESSES?: number | bigint | undefined;
    DNS_USE_GLOBAL_CACHE?: number | bigint | undefined;
    DOH_SSL_VERIFYHOST?: number | bigint | undefined;
    DOH_SSL_VERIFYPEER?: number | bigint | undefined;
    DOH_SSL_VERIFYSTATUS?: number | bigint | undefined;
    DOH_URL?: string | undefined;
    EGDSOCKET?: string | undefined;
    ENCODING?: string | undefined;
    EXPECT_100_TIMEOUT_MS?: number | bigint | undefined;
    FAILONERROR?: number | bigint | undefined;
    FILETIME?: number | bigint | undefined;
    FOLLOWLOCATION?: number | bigint | undefined;
    FORBID_REUSE?: number | bigint | undefined;
    FRESH_CONNECT?: number | bigint | undefined;
    FTPAPPEND?: number | bigint | undefined;
    FTPLISTONLY?: number | bigint | undefined;
    FTPPORT?: string | undefined;
    FTPSSLAUTH?: number | bigint | undefined;
    FTP_ACCOUNT?: string | undefined;
    FTP_ALTERNATIVE_TO_USER?: string | undefined;
    FTP_CREATE_MISSING_DIRS?: number | bigint | undefined;
    FTP_FILEMETHOD?: number | bigint | undefined;
    FTP_RESPONSE_TIMEOUT?: number | bigint | undefined;
    FTP_SKIP_PASV_IP?: number | bigint | undefined;
    FTP_SSL?: number | bigint | undefined;
    FTP_SSL_CCC?: number | bigint | undefined;
    FTP_USE_EPRT?: number | bigint | undefined;
    FTP_USE_EPSV?: number | bigint | undefined;
    FTP_USE_PRET?: number | bigint | undefined;
    GSSAPI_DELEGATION?: number | bigint | undefined;
    HAPPY_EYEBALLS_TIMEOUT_MS?: number | bigint | undefined;
    HAPROXYPROTOCOL?: number | bigint | undefined;
    HEADER?: number | bigint | undefined;
    HEADEROPT?: number | bigint | undefined;
    HSTS?: string | undefined;
    HSTS_CTRL?: number | bigint | undefined;
    HTTP09_ALLOWED?: number | bigint | undefined;
    HTTP200ALIASES?: string[] | undefined;
    HTTPAUTH?: number | bigint | undefined;
    HTTPGET?: number | bigint | undefined;
    HTTPHEADER?: string[] | undefined;
    HTTPPROXYTUNNEL?: number | bigint | undefined;
    HTTP_CONTENT_DECODING?: number | bigint | undefined;
    HTTP_TRANSFER_DECODING?: number | bigint | undefined;
    HTTP_VERSION?: number | bigint | undefined;
    IGNORE_CONTENT_LENGTH?: number | bigint | undefined;
    INFILESIZE?: number | bigint | undefined;
    INFILESIZE_LARGE?: number | bigint | undefined;
    INTERFACE?: string | undefined;
    IPRESOLVE?: number | bigint | undefined;
    ISSUERCERT?: string | undefined;
    ISSUERCERT_BLOB?: Uint8Array | undefined;
    KEEP_SENDING_ON_ERROR?: number | bigint | undefined;
    KEYPASSWD?: string | undefined;
    KRB4LEVEL?: string | undefined;
    KRBLEVEL?: string | undefined;
    LOCALPORT?: number | bigint | undefined;
    LOCALPORTRANGE?: number | bigint | undefined;
    LOGIN_OPTIONS?: string | undefined;
    LOW_SPEED_LIMIT?: number | bigint | undefined;
    LOW_SPEED_TIME?: number | bigint | undefined;
    MAIL_AUTH?: string | undefined;
    MAIL_FROM?: string | undefined;
    MAIL_RCPT?: string[] | undefined;
    MAIL_RCPT_ALLLOWFAILS?: number | bigint | undefined;
    MAXAGE_CONN?: number | bigint | undefined;
    MAXCONNECTS?: number | bigint | undefined;
    MAXFILESIZE?: number | bigint | undefined;
    MAXFILESIZE_LARGE?: number | bigint | undefined;
    MAXLIFETIME_CONN?: number | bigint | undefined;
    MAXREDIRS?: number | bigint | undefined;
    MAX_RECV_SPEED_LARGE?: number | bigint | undefined;
    MAX_SEND_SPEED_LARGE?: number | bigint | undefined;
    MIME_OPTIONS?: number | bigint | undefined;
    NETRC?: number | bigint | undefined;
    NETRC_FILE?: string | undefined;
    NEW_DIRECTORY_PERMS?: number | bigint | undefined;
    NEW_FILE_PERMS?: number | bigint | undefined;
    NOBODY?: number | bigint | undefined;
    NOPROGRESS?: number | bigint | undefined;
    NOPROXY?: string | undefined;
    NOSIGNAL?: number | bigint | undefined;
    PASSWORD?: string | undefined;
    PATH_AS_IS?: number | bigint | undefined;
    PINNEDPUBLICKEY?: string | undefined;
    PIPEWAIT?: number | bigint | undefined;
    PORT?: number | bigint | undefined;
    POST?: number | bigint | undefined;
    POST301?: number | bigint | undefined;
    POSTFIELDS?: string | Uint8Array | undefined;
    POSTFIELDSIZE?: number | bigint | undefined;
    POSTFIELDSIZE_LARGE?: number | bigint | undefined;
    POSTQUOTE?: string[] | undefined;
    POSTREDIR?: number | bigint | undefined;
    PREQUOTE?: string[] | undefined;
    PRE_PROXY?: string | undefined;
    PROTOCOLS?: number | bigint | undefined;
    PROXY?: string | undefined;
    PROXYAUTH?: number | bigint | undefined;
    PROXYHEADER?: string[] | undefined;
    PROXYPASSWORD?: string | undefined;
    PROXYPORT?: number | bigint | undefined;
    PROXYTYPE?: number | bigint | undefined;
    PROXYUSERNAME?: string | undefined;
    PROXYUSERPWD?: string | undefined;
    PROXY_CAINFO?: string | undefined;
    PROXY_CAINFO_BLOB?: Uint8Array | undefined;
    PROXY_CAPATH?: string | undefined;
    PROXY_CRLFILE?: string | undefined;
    PROXY_ISSUERCERT?: string | undefined;
    PROXY_ISSUERCERT_BLOB?: Uint8Array | undefined;
    PROXY_KEYPASSWD?: string | undefined;
    PROXY_PINNEDPUBLICKEY?: string | undefined;
    PROXY_SERVICE_NAME?: string | undefined;
    PROXY_SSLCERT?: string | undefined;
    PROXY_SSLCERTTYPE?: string | undefined;
    PROXY_SSLCERT_BLOB?: Uint8Array | undefined;
    PROXY_SSLKEY?: string | undefined;
    PROXY_SSLKEYTYPE?: string | undefined;
    PROXY_SSLKEY_BLOB?: Uint8Array | undefined;
    PROXY_SSLVERSION?: number | bigint | undefined;
    PROXY_SSL_CIPHER_LIST?: string | undefined;
    PROXY_SSL_OPTIONS?: number | bigint | undefined;
    PROXY_SSL_VERIFYHOST?: number | bigint | undefined;
    PROXY_SSL_VERIFYPEER?: number | bigint | undefined;
    PROXY_TLS13_CIPHERS?: string | undefined;
    PROXY_TLSAUTH_PASSWORD?: string | undefined;
    PROXY_TLSAUTH_TYPE?: string | undefined;
    PROXY_TLSAUTH_USERNAME?: string | undefined;
    PROXY_TRANSFER_MODE?: number | bigint | undefined;
    PUT?: number | bigint | undefined;
    QUOTE?: string[] | undefined;
    RANDOM_FILE?: string | undefined;
    RANGE?: string | undefined;
    REDIR_PROTOCOLS?: number | bigint | undefined;
    REFERER?: string | undefined;
    REQUEST_TARGET?: string | undefined;
    RESOLVE?: string[] | undefined;
    RESUME_FROM?: number | bigint | undefined;
    RESUME_FROM_LARGE?: number | bigint | undefined;
    RTSPHEADER?: string[] | undefined;
    RTSP_CLIENT_CSEQ?: number | bigint | undefined;
    RTSP_REQUEST?: number | bigint | undefined;
    RTSP_SERVER_CSEQ?: number | bigint | undefined;
    RTSP_SESSION_ID?: string | undefined;
    RTSP_STREAM_URI?: string | undefined;
    RTSP_TRANSPORT?: string | undefined;
    SASL_AUTHZID?: string | undefined;
    SASL_IR?: number | bigint | undefined;
    SERVER_RESPONSE_TIMEOUT?: number | bigint | undefined;
    SERVICE_NAME?: string | undefined;
    SOCKS5_AUTH?: number | bigint | undefined;
    SOCKS5_GSSAPI_NEC?: number | bigint | undefined;
    SOCKS5_GSSAPI_SERVICE?: string | undefined;
    SSH_AUTH_TYPES?: number | bigint | undefined;
    SSH_COMPRESSION?: number | bigint | undefined;
    SSH_HOST_PUBLIC_KEY_MD5?: string | undefined;
    SSH_HOST_PUBLIC_KEY_SHA256?: string | undefined;
    SSH_KNOWNHOSTS?: string | undefined;
    SSH_PRIVATE_KEYFILE?: string | undefined;
    SSH_PUBLIC_KEYFILE?: string | undefined;
    SSLCERT?: string | undefined;
    SSLCERTPASSWD?: string | undefined;
    SSLCERTTYPE?: string | undefined;
    SSLCERT_BLOB?: Uint8Array | undefined;
    SSLENGINE?: string | undefined;
    SSLENGINE_DEFAULT?: number | bigint | undefined;
    SSLKEY?: string | undefined;
    SSLKEYPASSWD?: string | undefined;
    SSLKEYTYPE?: string | undefined;
    SSLKEY_BLOB?: Uint8Array | undefined;
    SSLVERSION?: number | bigint | undefined;
    SSL_CIPHER_LIST?: string | undefined;
    SSL_EC_CURVES?: string | undefined;
    SSL_ENABLE_ALPN?: number | bigint | undefined;
    SSL_ENABLE_NPN?: number | bigint | undefined;
    SSL_FALSESTART?: number | bigint | undefined;
    SSL_OPTIONS?: number | bigint | undefined;
    SSL_SESSIONID_CACHE?: number | bigint | undefined;
    SSL_VERIFYHOST?: number | bigint | undefined;
    SSL_VERIFYPEER?: number | bigint | undefined;
    SSL_VERIFYSTATUS?: number | bigint | undefined;
    STREAM_WEIGHT?: number | bigint | undefined;
    SUPPRESS_CONNECT_HEADERS?: number | bigint | undefined;
    TCP_FASTOPEN?: number | bigint | undefined;
    TCP_KEEPALIVE?: number | bigint | undefined;
    TCP_KEEPIDLE?: number | bigint | undefined;
    TCP_KEEPINTVL?: number | bigint | undefined;
    TCP_NODELAY?: number | bigint | undefined;
    TELNETOPTIONS?: string[] | undefined;
    TFTP_BLKSIZE?: number | bigint | undefined;
    TFTP_NO_OPTIONS?: number | bigint | undefined;
    TIMECONDITION?: number | bigint | undefined;
    TIMEOUT?: number | bigint | undefined;
    TIMEOUT_MS?: number | bigint | undefined;
    TIMEVALUE?: number | bigint | undefined;
    TIMEVALUE_LARGE?: number | bigint | undefined;
    TLS13_CIPHERS?: string | undefined;
    TLSAUTH_PASSWORD?: string | undefined;
    TLSAUTH_TYPE?: string | undefined;
    TLSAUTH_USERNAME?: string | undefined;
    TRANSFERTEXT?: number | bigint | undefined;
    TRANSFER_ENCODING?: number | bigint | undefined;
    UNIX_SOCKET_PATH?: string | undefined;
    UNRESTRICTED_AUTH?: number | bigint | undefined;
    UPKEEP_INTERVAL_MS?: number | bigint | undefined;
    UPLOAD?: number | bigint | undefined;
    UPLOAD_BUFFERSIZE?: number | bigint | undefined;
    URL?: string | undefined;
    USERAGENT?: string | undefined;
    USERNAME?: string | undefined;
    USERPWD?: string | undefined;
    USE_SSL?: number | bigint | undefined;
    VERBOSE?: number | bigint | undefined;
    WILDCARDMATCH?: number | bigint | undefined;
    XOAUTH2_BEARER?: string | undefined;
};
