'use strict';

const REDIR_GET_ALL = 0;
const REDIR_POST_301 = 1;
const REDIR_POST_302 = 2;
const REDIR_POST_303 = 4;
const REDIR_POST_ALL = REDIR_POST_301 | REDIR_POST_302 | REDIR_POST_303;

/** @enum */
module.exports = {
	REDIR_GET_ALL,
	REDIR_POST_301,
	REDIR_POST_302,
	REDIR_POST_303,
	REDIR_POST_ALL,
};
